
connection:
  server:
    host: pay-server
    port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://${connection.server.host}:${connection.server.port}/eureka/
  instance:
    hostname: pay-alipay

server:
  port: 8091
spring:
  application:
    name: pay-alipay