connection:
  server:
    host: pay-server
    port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://${connection.server.host}:${connection.server.port}/eureka/

server:
  port: 8092
spring:
  application:
    name: pay-weixin