server:
  port: 8762
  port-node: 8761

eureka:
  instance:
    hostname: pay-server
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port-node}/eureka/
spring:
  application:
    name: pay-server
logging:
  level:
    org.springframework: debug
